name: env-demo-cmems-arco
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - aiohttp~=3.8.1
  - cartopy~=0.20.2
  - fsspec
  - matplotlib
  - numpy
  - requests
  - xarray
  - zarr
